plugin_blacklist:
# common
- actuator_control
- safety_area
- hil
# extras
- altitude
- debug_value
- image_pub
- px4flow
#- vibration
- wheel_odometry

plugin_whitelist:
- 'sys_*'
- ftp
- vision_pose_estimate
- vision_speed_estimate
