version: "3.8"
services:
  ##############################################################
  ## Container for ROS-Devel Workspace
  ## command: sudo docker-compose up ros-devel
  ## Args:  - ROS_DISTRIBUTION=kinetic | melodic | noetic
  ##        - BUILD_TYPE= devel | install
  ##############################################################
  ros-devel:
    build:
      context: .
      dockerfile: Dockerfile.ros
      args:
        - ROS_DISTRIBUTION=melodic
        - BUILD_TYPE=devel
    container_name: ros-devel
    stdin_open: true
    tty: true
    network_mode: "host"
    environment:
      - ROS_DISTRO=melodic
    volumes:
      - "./src:/root/catkin_ws/src:rw"
    # ports:
    #   - "11311:11311"
    #   - "19997:19997"
    # devices:
    #  - /dev/ttyACM0:/dev/ttyACM0
    #  - /dev/input/js0
    command: roscore

  ##############################################################
  ## Container for ROS-Install Workspace
  ## command: sudo docker-compose up ros-install
  ## Args:  - ROS_DISTRIBUTION=kinetic | melodic | noetic
  ##        - BUILD_TYPE= devel | install
  ##############################################################
  apm-sitl:
    build:
      context: .
      dockerfile: Dockerfile.apm
      args:
        - ROS_DISTRIBUTION=melodic
    container_name: apm-sitl
    stdin_open: true
    tty: true
    network_mode: "host"
    environment:
      - ROS_DISTRO=melodic
    # ports:
    #   - "11311:11311"
    #   - "19997:19997"
    # devices:
    #   - /dev/ttyACM0:/dev/ttyACM0
    #   - /dev/input/js0
    command: bash
  
