version: "3.3"
services:
  ##############################################################
  ## Container for ROS-Devel Workspace
  ## command: sudo docker-compose up ros-devel
  ## Args:  - ROS_DISTRIBUTION=kinetic | melodic | noetic
  ##        - BUILD_TYPE= devel | install
  ##############################################################
  ros-devel:
    build:
      context: .
      dockerfile: Dockerfile.ros
      args:
        - ROS_DISTRIBUTION=kinetic
        - BUILD_TYPE=devel
    container_name: ros-devel 
    stdin_open: true
    tty: true
    network_mode: "host"
    environment:
      - ROS_DISTRO=kinetic
      - LD_LIBRARY_PATH=/opt/vc/lib
      - ROS_MASTER_URI=http://192.168.99.219:11311/
      - ROS_HOSTNAME=192.168.99.10
      - ROS_IP=192.168.99.10
    volumes:
      - "./src:/root/catkin_ws/src:rw"
      - "/opt/vc:/opt/vc:rw"
    # ports:
    #   - "11311:11311"
    #   - "19997:19997"
      # - "9000:9000"
    devices:
      - /dev/vchiq
    #  - /dev/input/js0
    command: roslaunch /ros-app.launch
  
  
  ##############################################################
  ## Container raspicam
  ## command: 
  ## Args:  - 
  ##############################################################
  raspi-cam-node:
    image: dtur3/r3-raspicam
    container_name: "raspicam-node"
    stdin_open: true
    tty: true
    network_mode: "host"
    environment:
      - ROS_DISTRO=kinetic
      - LD_LIBRARY_PATH=/opt/vc/lib
      - ROS_MASTER_URI=http://192.168.169.219:11311/
      - ROS_HOSTNAME=chirag-desktop.local
      - ROS_IP=chirag-desktop.local
    volumes:
      - "./src:/root:rw"
    devices: 
      - /dev/vcsm
      - /dev/vchiq
    command: roslaunch /root/visual_odometry/raspicam_node/launch/camerav2_410x308_30fps.launch enable_raw:=true --wait --screen  #raspicam_node camerav2_410x308_30fps.launch --wait --screen
 